apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      auto.create.topics.enable: false
      log.cleaner.backoff.ms: 15000
      log.cleaner.dedupe.buffer.size: 134217728
      log.cleaner.enable: true
      log.cleaner.io.buffer.load.factor: 0.9
      log.cleaner.threads: 8
      log.cleanup.policy: delete
      log.retention.bytes: 107374182400
      log.retention.check.interval.ms: 300000
      log.retention.ms: 1680000
      log.roll.ms: 7200000
      log.segment.bytes: 1073741824
    storage:
      type: persistent-claim
      size: 200Gi
      class: ${DEFAULT_SC}
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 20Gi
      class: ${DEFAULT_SC}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: flows-export
  labels:
    strimzi.io/cluster: "kafka-cluster"
spec:
  partitions: 24
  replicas: 1
